#
# linux-nfs/support/nfs/Makefile
#
TOP	= ../../
LIBNAME	= libnfs.a
OBJS	= exports.o rmtab.o xio.o \
	  rpcmisc.o rpcdispatch.o xlog.o xmalloc.o wildmat.o \
	  nfssvc.o nfsclient.o nfsexport.o getfh.o nfsctl.o \
	  lockdsvc.o svc_socket.o cacheio.o closeall.o

include $(TOP)rules.mk

install::
	@:
