.TH NHFSRUN 8 "26 Feb 2000"
.SH NAME
nhfsrun \- Run
.B nhfsstone
over multiple loads
.SH SYNOPSIS
.B nhfsrun <suffix>
.SH DESCRIPTION
Runs
.B nhfsstone
with a range of different loads and put results in a file called
.BR run.<suffix> .
.SH SEE ALSO
.BR nhfsstone (8),
.BR nhfsnums (8),
.BR nhfsgraph (8)
