#!/bin/sh
#
# @(#)nhfsgraph.sh 1.3 89/07/07 Copyright (c) 1989, Legato Systems, Inc.
#
# See DISCLAIMER file for restrictions
#

#
# Usage: nhfsgraph <graphfile> ...
#
# Produce a PostScript graph of nhfsstone numbers.
# Graphfile is a file with number pairs in plot(5) format derived
# from runs of nhfsstone at different loads (see "nhfsrun" and "nhfsnums"
# scripts.
#
# If you want something other than PostScript output replace "psplot"
# with "plot". See plot(1) for more details.
#

LABEL="x=Load (calls/sec) y=Response (msec/call)"

cat $* \
    | graph -b -u .1 -h 1.2 -g 2 -l "$LABEL" -x 10 80 10 | psplot
