#!/bin/sh
#
# @(#)nhfsnums.sh 1.3 89/07/07 Copyright (c) 1989, Legato Systems, Inc.
#
# See DISCLAIMER file for restrictions
#

#
# Usage: nhfsnums <numsfile> ...
#
# Collect raw numbers from nhfsstone output and print in plot(5) format.
# The nums files should be named "run.xxx" where xxx is a name related
# to the numbers gathered. Each file will produce one line with a label
# that is the file suffix (the part following the dot.)
#

for i in $*; do
	RUNNAME=`echo $i | sed -e 's/.*\\.//'`
	awk '{ print $5 "	" $7 }' $i \
	    | sort -n\
	    | sed -e "\$s/\$/	\"$RUNNAME\"/"
done
