.TH NHFSNUMS 8 "26 Feb 2000"
.SH NAME
nhfsnums \- Convert
.B nhfsrun
output to
.BR plot (5)
.SH SYNOPSIS
.B nhfsnums <numsfiles>
.SH DESCRIPTION
Converts raw numbers from nhfsstone output into
.BR plot (5)
format.  The
.B <numsfiles>
should be named 
.BR run.xxx ,
where
.B xxx
is a name related to the numbers gathered.
Each file will produce one line with a label
that is the file suffix (the part following the dot).
.SH SEE ALSO
.BR nhfsstone (8),
.BR nhfsrun (8),
.BR nhfsgraph (8)
