#!/bin/bash -p
# nfsmount calls this script when mounting a filesystem with locking
# enabled, but when statd does not seem to be running (based on
# /var/run/rpc.statd.pid).
# It should run statd with whatever flags are apropriate for this
# site.
PATH=/sbin:/usr/sbin
if systemctl start statd.service
then :
else
    exec rpc.statd --no-notify
fi
